#!/bin/bash

# General bash configuration.
export TCONF=$HOME/tconf

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# start fish shell
WHICH_FISH="$(which fish)"
if [[ "$-" =~ i && -x "${WHICH_FISH}" && ! "${SHELL}" -ef "${WHICH_FISH}" ]]; then
  # Safeguard to only activate fish for interactive shells and only if fish
  # shell is present and executable. Verify that this is a new session by
  # checking if $SHELL is set to the path to fish. If it is not, we set
  # $SHELL and start fish.
  #
  # If this is not a new session, the user probably typed 'bash' into their
  # console and wants bash, so we skip this.
  exec env SHELL="${WHICH_FISH}" "${WHICH_FISH}" -i
fi

export SHELL="$(which $0)"
export SHELL_NAME="bash"

echo "// $(date "+%A, %b %d") • Week $(date "+%V") • $SHELL_NAME"

# History configuration
# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
# for setting history length
HISTSIZE=1000
HISTFILESIZE=2000
# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

if dircolors &> /dev/null; then
  DIRCOLORS=$TCONF/themes/current-theme/dircolors
  (test -r $DIRCOLORS && eval "$(dircolors -b $DIRCOLORS)" || eval "$(dircolors -b)")
fi

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot=$(cat /etc/debian_chroot)
fi

if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi

# enable programmable completion features
if ! shopt -oq posix; then
  # UGH! This is so slow!
  if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
  # Git
  if [ -f /usr/share/git/completion/git-completion.bash ]; then
    . /usr/share/git/completion/git-completion.bash
  fi
  if [ -f /usr/share/git/completion/git-prompt.sh ]; then
    . /usr/share/git/completion/git-prompt.sh
  elif [ -f /usr/local/etc/bash_completion.d/git-prompt.sh ]; then
    . /usr/local/etc/bash_completion.d/git-prompt.sh
  elif [ -f /opt/brew/opt/git/etc/bash_completion.d/git-prompt.sh ]; then
    . /opt/brew/opt/git/etc/bash_completion.d/git-prompt.sh
  fi
fi

# Load the config if it exists.
load() {
  if [ -f "$1" ]; then
    . "$1"
  fi
}

# Load modular config
MODULES="vars functions aliases ps1"
for MODULE in $MODULES; do
    load "$TCONF/shell/$MODULE"
    load "$TCONF/local/shell/$MODULE"
    load "$TCONF/priv/shell/$MODULE"
done

# Load local configs
load "$TCONF/local/shell/bashrc"
load "$TCONF/priv/shell/bashrc"
load "$TCONF/secret/shell/bashrc"
