[user]
name = "Tim Allclair"
email = "timallclair@gmail.com"

[ui]
editor = ["micro"]

[aliases]
s = ["status"]

# For your custom 'start' shell script, we escape to the shell via `util exec`
# start = ["util", "exec", "--", "bash", "-c", "git fetch upstream && git checkout -b \"$1\" upstream/master", ""]
