[user]
name = "Tim Allclair"
email = "timallclair@gmail.com"

[ui]
editor = ["micro"]
merge-editor = ":builtin"
conflict-marker-style = "git"

[colors]
red = "red"

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
"immutable_heads()" = "trunk() | tags() | remote_bookmarks(upstream)"

[aliases]
s = ["status"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "@"]

# For your custom 'start' shell script, we escape to the shell via `util exec`
# start = ["util", "exec", "--", "bash", "-c", "git fetch upstream && git checkout -b \"$1\" upstream/master", ""]
