;; AUTOMATICALLY GENERATED BY CHEZMOI - DO NOT EDIT
;; Local initialization template

;; Natively load the shared tconf init.el
(load-file "~/tconf/emacs/init.el")

;; Location to store autosaves in
(set-autosave-dir "~/.config/emacs/autosaves/")

;; Location to store backups in
(set-backup-dir "~/.config/emacs/backups/")
