# Connect agents
if [[ -z "$SSH_CLIENT" ]] && [[ -z "$SSH_TTY" ]]; then
   # Only connect SSH agent if not running over SSH.
   source ${HOME}/.ssh-agent-info > /dev/null
fi
source ${HOME}/.gpg-agent-info

# The next line updates PATH for the Google Cloud SDK.
if [ -f ${HOME}/opt/google-cloud-sdk/path.bash.inc ]; then
  . "${HOME}/opt/google-cloud-sdk/path.bash.inc"
fi

# The next line enables shell command completion for gcloud.
if [ -f ${HOME}/opt/google-cloud-sdk/completion.bash.inc ]; then
   . "${HOME}/opt/google-cloud-sdk/completion.bash.inc"
fi

# Kubernetes bash completions.
source <(kubectl completion bash)

if [ -d "$HOME/.cargo/bin" ]; then
   export PATH="$HOME/.cargo/bin:$PATH"
fi
