unalias ls  # Mac compatability fix

if command -v brew &> /dev/null; then
    eval "$(brew shellenv)"
fi

if command -v kubectl &> /dev/null; then
    # Kubernetes bash completions.
    source <(kubectl completion bash)
    . "$TCONF/projects/kubernetes/etc/bashrc"
fi

[[ -s "${HOME}/.gvm/scripts/gvm" ]] && source "${HOME}/.gvm/scripts/gvm"

[[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]] && . "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"

# export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

/usr/bin/ssh-add --apple-load-keychain -q